apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: data-processing-job-4g-capital
  namespace: default
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "4g-capital-backend:us-central1:backend-database"
        run.googleapis.com/vpc-access-connector: "4g-capital-vpc-connector"
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          maxRetries: 3
          timeoutSeconds: 600
          serviceAccountName: 4g-capital-backend-service-account@4g-capital.iam.gserviceaccount.com
          containers:
          - image: gcr.io/4g-capital-backend/data-processing-image
            command:
            - python
            - run_task.py
            args:
            - --input
            - gs://4g-capital-bucket/input-data.json
            - --output
            - gs://4g-capital-bucket/output-data.json
            env:
            - name: DATABASE_URL
              value: "postgres://backend_user:4gcapitalpassword@4g-capital-backend-database.us-central1.sql.googleapis.com:5432/4g-capital_db"
            resources:
              limits:
                cpu: "1"
                memory: "512Mi"
          volumes:
          - name: secret-volume
            secret:
              secretName: 4g-capital-secret
              items:
              - key: SECRET_VERSION
                path: secret-path
          - name: empty-dir
            emptyDir:
              sizeLimit: 1Gi
              medium: Memory
