apiVersion: v1
kind: Service
metadata:
  name: frontend-service  # Updated name to be DNS-compliant
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: 4g-react-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 4g-react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 4g-react-frontend
  template:
    metadata:
      labels:
        app: 4g-react-frontend
    spec:
      containers:
        - name: 4g-react-frontend
          image: kiplongu/4g-react-frontend:latest
          ports:
            - containerPort: 80
